# Generated by Django 6.0.2 on 2026-03-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapi', '0005_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
