# Generated by Django 6.0.2 on 2026-03-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapi', '0006_delete_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
